### ISSUE TITLE
TO_EnableChannelCmd_t Overrides Breaks The Build

### ISSUE THREAD

**Issue by lorenzo-gomez-windhover** [WindhoverLabs/airliner#96]
```
INFO:squeezer:Processing overrides...
ERROR:squeezer:The symbol name with name DS_HkPacket_t does not exist.
WARNING:squeezer:The symbol "DS_HkPacket_t" does not exist in the database.Field override will not be processed.
ERROR:squeezer:The symbol name with name DS_FileInfo_t does not exist.
WARNING:squeezer:The symbol "DS_FileInfo_t" does not exist in the database.Field override will not be processed.
ERROR:squeezer:The symbol name with name DS_DestPathCmd_t does not exist.
WARNING:squeezer:The symbol "DS_DestPathCmd_t" does not exist in the database.Field override will not be processed.
ERROR:squeezer:The symbol name with name DS_DestBaseCmd_t does not exist.
WARNING:squeezer:The symbol "DS_DestBaseCmd_t" does not exist in the database.Field override will not be processed.
ERROR:squeezer:The symbol name with name DS_DestExtCmd_t does not exist.
WARNING:squeezer:The symbol "DS_DestExtCmd_t" does not exist in the database.Field override will not be processed.
Traceback (most recent call last):
  File "squeezer.py", line 306, in <module>
    main()
  File "squeezer.py", line 299, in main
    args.func(args)
  File "squeezer.py", line 212, in singleton_mode_handler
    run_msg_def_overrides(args.singleton_yaml_path, args.output_file)
  File "squeezer.py", line 157, in run_msg_def_overrides
    msg_def_overrides.process_def_overrides(yaml_overrides_dict, db_handle)
  File "/home/penguin/Desktop/4-27-22/squeaky-weasel/software/airliner/public/core/tools/auto-yamcs/src/msg_def_overrides.py", line 264, in process_def_overrides
    process_def_overrides(def_overrides['modules'][module], db_handle, module_elf)
  File "/home/penguin/Desktop/4-27-22/squeaky-weasel/software/airliner/public/core/tools/auto-yamcs/src/msg_def_overrides.py", line 260, in process_def_overrides
    process_symbol_override(override, module_elf, db_handle)
  File "/home/penguin/Desktop/4-27-22/squeaky-weasel/software/airliner/public/core/tools/auto-yamcs/src/msg_def_overrides.py", line 213, in process_symbol_override
    type_record = get_field_type_record(symbol_override['parent'], symbol_override['member'], db_handle)
  File "/home/penguin/Desktop/4-27-22/squeaky-weasel/software/airliner/public/core/tools/auto-yamcs/src/msg_def_overrides.py", line 175, in get_field_type_record
    field_record = list(db_handle['fields'].rows_where('symbol=? and name=?', [field_symbol, field_name]))[0]
IndexError: list index out of range
Makefile:148: recipe for target 'workspace' failed
make: *** [workspace] Error 1
```

**Comment by lorenzo-gomez-windhover** [comment]
Has been resolved in 3557b587dba8f33424e0fa7dce0e0d1bdc56ca56
